baseURL = "https://marcdcls.github.io"
disableLanguages = []
disqusShortname = ""
paginate = "4"
summaryLength = "30"
theme = "airspace-hugo"

################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
title = "Marc Duclusaud's website"
weight = 1

######################### English Navigation #############################
# Header menu
[[Languages.en.menu.main]]
URL = "projects"
name = "Projects"
weight = 1
[[Languages.en.menu.main]]
URL = "about"
name = "About"
weight = 2

# Footer menu
[[Languages.en.menu.footer]]
URL = "projects"
name = "Projects"
weight = 1
[[Languages.en.menu.footer]]
URL = "about"
name = "About"
weight = 2

################################ French Language #########################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
title = "Site de Marc Duclusaud"
weight = 2

######################### French Navigation ##############################
# Sections en haut de page
[[Languages.fr.menu.main]]
URL = "projects"
name = "Projets"
weight = 1
[[Languages.fr.menu.main]]
URL = "about"
name = "Qui suis-je ?"
weight = 2

# Sections en fin de page
[[Languages.fr.menu.footer]]
URL = "projects"
name = "Projets"
weight = 1
[[Languages.fr.menu.footer]]
URL = "about"
name = "Qui suis-je ?"
weight = 2



[markup.goldmark.renderer]
unsafe = true
[outputs]
home = ["HTML"]
[params]
mainSections = ["projects"]
author = "Marc Duclusaud"
description = ""
email = "marc.duclusaud@gmail.com"
google_analitycs_id = ""
location = ""
logo = "" # "images/misc/M_logo.webp"
logo_width = "40px"
mobile = "+33 6 77 47 13 45"
multi_author = false
phone = "+33 6 77 47 13 45"
[params.cookies]
enable = false
expire_days = 2

# [params.gmap]
# enable = true
# gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
# map_latitude = "44.806710"
# map_longitude = "-0.605199"
# map_marker = "images/marker.png"

[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = ""

# Réseaux sociaux
[[params.social]]
icon = "ion-social-github"
link = "https://github.com/MarcDcls"
[[params.social]]
icon = "ion-social-linkedin"
link = "https://www.linkedin.com/in/marc-duclusaud-260b46223"

# [[params.social]]
# icon = "images/misc/icon_eirlab.png"
# link = "https://www.eirlab.net"

# [[params.social]]
# icon = "ion-social-twitter"
# link = "https://twitter.com/"
# [[params.social]]
# icon = "ion-social-facebook"
# link = "https://www.facebook.com/"
# [[params.social]]
# icon = "ion-social-youtube"
# link = "https://www.youtube.com/user/"
